spring:
  main:
    web-application-type: none
interval: 60000
login-url: http://10.89.6.35:11210/webapi/setUserInfo
licenseCode: WuHWZOQT # 125
thirdAppId: JTGSYYZXPT
pspaceUsername: JTGSYYPT
pspacePassword: JTGSYYPT@2022!
data-url: http://10.89.6.35:11210/webapi/PSpaceQuery.ashx
#data-url: http://127.0.0.1:6666/mock/data
tags: \C210249FI00001010,\C210249FI00001020,\C210249FI00001030,\C210249FI00001040,\C210249FI00001050,\C210249FI00001060,\C210249FI0000501A,\C210249FI0000502A,\C210249FI0000503A,\C210249PI0000501A,\C210249PI0000502A,\C210249PI0000503A,\C250265FI00005100,\C250265PI00001050,\D250432FI00005050,\D250432FI00005060,\D250432PI00001190,\C250090FN00002020,\C250090FN00002030,\C250090FN00002040,\C250090PI00001030
push-url: http://localhost:6666/gas/add
push-multi-url: http://localhost:6666/gas/multi/add
region: xinan
